version: '3'
services:
  igdb-api:
    image: kalex375/igdb-api
    restart: always
    container_name: igdb-api
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      RAPID_KEY: ${RAPID_KEY}
      RAPID_HOST: ${RAPID_HOST}
    ports:
      - "3030:3030"
    networks:
      - gq

#  mailhog:
#    image: 'mailhog/mailhog:latest'
#    ports:
#      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#    networks:
#      - sail
networks:
  gq:
    driver: bridge
